constants = {
  SUN_DIAMETER: 1392700,
  LIGHT_YEAR: 9460730472580.8, 
  SPECT_CLASS: { //for mapping from spect class to kelvin
    O: {min:30000, step:2000, radius:10}, 
    B: {min:10000, step:2000, radius: 5}, 
    A: {min: 7500, step: 250, radius: 1.5}, 
    F: {min: 6000, step: 150, radius: 1.3}, 
    G: {min: 5200, step:  80, radius: 1}, 
    K: {min: 3700, step: 150, radius: 0.8}, 
    M: {min: 2400, step: 130, radius: 0.5}, 
    R: {min: 1000, step: 140, radius: 0.1}, 
    N: {min: 1000, step: 140, radius: 0.1}, 
    S: {min: 1000, step: 140, radius: 0.1}
  },
  LUMINOSITY_CLASS: {  //for mapping from star type to radius
    'D'  : {radius: 0.1, label:'白色矮星'},
    'VII': {radius: 0.1, label:'白色矮星'},
    'VI' : {radius: 0.5, label:'準矮星'},
    'sd' : {radius: 0.5, label:'準矮星'},
    'V'  : {radius: 1,   label:'主系列星（矮星）'},
    'IV' : {radius: 3,   label:'準巨星'},
    'III': {radius: 5,   label:'通常の巨星'},
    'II' : {radius: 7,   label:'輝巨星'},
    'Ib' : {radius: 10,  label:'暗い超巨星'},
    'Iab': {radius: 10,  label:'超巨星'},
    'Ia' : {radius: 10,  label:'明るい超巨星'},
    'Ia+': {radius: 100, label:'極超巨星'},
    'Ia0': {radius: 100, label:'極超巨星'},
  },
  symbols: {
    'And': {label: 'アンドロメダ座'    , filters:['秋の星座']},
    'Mon': {label: 'いっかくじゅう座'  , filters:['冬の星座']},
    'Sgr': {label: 'いて座'            , filters:['十二星座', '夏の星座']},
    'Del': {label: 'いるか座'          , filters:['夏の星座']},
    'Ind': {label: 'インディアン座'    , filters:['南天の星座']},
    'Psc': {label: 'うお座'            , filters:['十二星座', '秋の星座']},
    'Lep': {label: 'うさぎ座'          , filters:['冬の星座']},
    'Boö': {label: 'うしかい座'        , filters:['春の星座']},
    'Hya': {label: 'うみへび座'        , filters:['春の星座']},
    'Eri': {label: 'エリダヌス座'      , filters:['冬の星座']},
    'Tau': {label: 'おうし座'          , filters:['十二星座', '冬の星座']},
    'CMa': {label: 'おおいぬ座'        , filters:['冬の星座']},
    'Lup': {label: 'おおかみ座'        , filters:['夏の星座', '南天の星座']},
    'UMa': {label: 'おおぐま座'        , filters:['春の星座', '北天の星座']},
    'Vir': {label: 'おとめ座'          , filters:['十二星座', '春の星座']},
    'Ari': {label: 'おひつじ座'        , filters:['十二星座', '秋の星座', '冬の星座']},
    'Ori': {label: 'オリオン座'        , filters:['冬の星座']},
    'Cas': {label: 'カシオペヤ座'      , filters:['秋の星座', '北天の星座']},
    'Dor': {label: 'かじき座'          , filters:['南天の星座']},
    'Cnc': {label: 'かに座'            , filters:['十二星座', '春の星座']},
    'Com': {label: 'かみのけ座'        , filters:['春の星座']},
    'Cha': {label: 'カメレオン座'      , filters:['南天の星座']},
    'Crv': {label: 'からす座'          , filters:['春の星座']},
    'CrB': {label: 'かんむり座'        , filters:['春の星座']},
    'Pic': {label: 'がか座'            , filters:['南天の星座']},
    'Tuc': {label: 'きょしちょう座'    , filters:['南天の星座']},
    'Cam': {label: 'きりん座'          , filters:['冬の星座', '北天の星座']},
    'Aur': {label: 'ぎょしゃ座'        , filters:['冬の星座']},
    'Cet': {label: 'くじら座'          , filters:['秋の星座']},
    'Pav': {label: 'くじゃく座'        , filters:['南天の星座']},
    'Cep': {label: 'ケフェウス座'      , filters:['秋の星座', '北天の星座']},
    'Cen': {label: 'ケンタウルス座'    , filters:['南天の星座']},
    'Mic': {label: 'けんびきょう座'    , filters:['秋の星座']},
    'CMi': {label: 'こいぬ座'          , filters:['冬の星座']},
    'Equ': {label: 'こうま座'          , filters:['秋の星座']},
    'Vul': {label: 'こぎつね座'        , filters:['夏の星座']},
    'UMi': {label: 'こぐま座'          , filters:['春の星座', '北天の星座']},
    'LMi': {label: 'こじし座'          , filters:['春の星座']},
    'Crt': {label: 'コップ座'          , filters:['春の星座']},
    'Lyr': {label: 'こと座'            , filters:['夏の星座']},
    'Cir': {label: 'コンパス座'        , filters:['南天の星座']},
    'Ara': {label: 'さいだん座'        , filters:['南天の星座']},
    'Sco': {label: 'さそり座'          , filters:['十二星座', '夏の星座']},
    'Tri': {label: 'さんかく座'        , filters:['秋の星座']},
    'Leo': {label: 'しし座'            , filters:['十二星座', '春の星座']},
    'Nor': {label: 'じょうぎ座'        , filters:['南天の星座']},
    'Sct': {label: 'たて座'            , filters:['夏の星座']},
    'Cae': {label: 'ちょうこくぐ座'    , filters:['冬の星座']},
    'Scl': {label: 'ちょうこくしつ座'  , filters:['秋の星座']},
    'Gru': {label: 'つる座'            , filters:['秋の星座']},
    'Lib': {label: 'てんびん座'        , filters:['十二星座', '夏の星座']},
    'Men': {label: 'テーブルさん座'    , filters:['南天の星座']},
    'Lac': {label: 'とかげ座'          , filters:['秋の星座']},
    'Hor': {label: 'とけい座'          , filters:['南天の星座']},
    'Vol': {label: 'とびうお座'        , filters:['南天の星座']},
    'Pup': {label: 'とも座'            , filters:['アルゴ4星座', '南天の星座']},
    'Mus': {label: 'はえ座'            , filters:['南天の星座']},
    'Cyg': {label: 'はくちょう座'      , filters:['夏の星座']},
    'Oct': {label: 'はちぶんぎ座'      , filters:['南天の星座']},
    'Col': {label: 'はと座'            , filters:['冬の星座']},
    'Aps': {label: 'ふうちょう座'      , filters:['南天の星座']},
    'Gem': {label: 'ふたご座'          , filters:['十二星座', '冬の星座']},
    'Oph': {label: 'へびつかい座'      , filters:['夏の星座']},
    'Ser': {label: 'へび座'            , filters:['夏の星座']},
    'Her': {label: 'ヘルクレス座'      , filters:['夏の星座']},
    'Peg': {label: 'ペガスス座'        , filters:['秋の星座']},
    'Per': {label: 'ペルセウス座'      , filters:['秋の星座']},
    'Phe': {label: 'ほうおう座'        , filters:['秋の星座', '南天の星座']},
    'Vel': {label: 'ほ座'              , filters:['アルゴ4星座', '南天の星座']},
    'Tel': {label: 'ぼうえんきょう座'  , filters:['南天の星座']},
    'Ant': {label: 'ポンプ座'          , filters:['春の星座']},
    'Aqr': {label: 'みずがめ座'        , filters:['十二星座', '秋の星座']},
    'Hyi': {label: 'みずへび座'        , filters:['南天の星座']},
    'CrA': {label: 'みなみのかんむり座', filters:['夏の星座']},
    'Cru': {label: 'みなみじゅうじ座'  , filters:['南天の星座']},
    'PsA': {label: 'みなみのうお座'    , filters:['秋の星座']},
    'TrA': {label: 'みなみのさんかく座', filters:['南天の星座']},
    'Cap': {label: 'やぎ座'            , filters:['十二星座', '秋の星座']},
    'Lyn': {label: 'やまねこ座'        , filters:['春の星座']},
    'Sge': {label: 'や座'              , filters:['夏の星座']},
    'Pyx': {label: 'らしんばん座'      , filters:['アルゴ4星座', '南天の星座']},
    'Car': {label: 'りゅうこつ座'      , filters:['アルゴ4星座', '南天の星座']},
    'Dra': {label: 'りゅう座'          , filters:['夏の星座', '北天の星座']},
    'CVn': {label: 'りょうけん座'      , filters:['春の星座']},
    'Ret': {label: 'レチクル座'        , filters:['南天の星座']},
    'Sex': {label: 'ろくぶんぎ座'      , filters:['春の星座']},
    'For': {label: 'ろ座'              , filters:['秋の星座']},
    'Aql': {label: 'わし座'            , filters:['夏の星座']},
  },
  additionalConstellations: {
    "春の大三角": {label: "春の大三角", filters:[], "NearBy": ["Boö", "Vir", "Leo"]},
    "春の大曲線": {label: "春の大曲線", filters:[], "NearBy": ["Boö", "Vir", "UMa"]},
    //"春の大四辺形": {label: "春の大四辺形", filters:[], "NearBy": ["Boö", "Vir", "Leo", "CVn"]},
    "夏の大三角": {label: "夏の大三角", filters: [], "NearBy": ["Lyr", "Cyg", "Aql"]},
    "秋の四辺形": {label: "秋の四辺形", filters:[], "NearBy": ["And", "Peg"]},
    "冬の大三角": {label: "冬の大三角", filters: [], "NearBy": ["CMa", "CMi", "Ori"]},
    //"冬のダイヤモンド":{label: "冬のダイヤモンド", filters: [], "NearBy": ["CMa", "CMi", "Ori", "Tau"]},
    "北斗七星": {label: "北斗七星", filters: [], "NearBy": ["UMa"]},
  }
};