constants = {
  SPECT_CLASS: { //for mapping from spect class to kelvin
    O: {min:30000, step:2000, radius:10}, 
    B: {min:10000, step:2000, radius: 5}, 
    A: {min: 7500, step: 250, radius: 1.5}, 
    F: {min: 6000, step: 150, radius: 1.3}, 
    G: {min: 5200, step:  80, radius: 1}, 
    K: {min: 3700, step: 150, radius: 0.8}, 
    M: {min: 2400, step: 130, radius: 0.5}, 
    R: {min: 1000, step: 140, radius: 0.1}, 
    N: {min: 1000, step: 140, radius: 0.1}, 
    S: {min: 1000, step: 140, radius: 0.1}
  },
  LUMINOSITY_CLASS: {  //for mapping from star type to radius
    'D'  : {radius: 0.1, label:'白色矮星'},
    'VII': {radius: 0.1, label:'白色矮星'},
    'VI' : {radius: 0.5, label:'準矮星'},
    'sd' : {radius: 0.5, label:'準矮星'},
    'V'  : {radius: 1,   label:'主系列星（矮星）'},
    'IV' : {radius: 3,   label:'準巨星'},
    'III': {radius: 5,   label:'通常の巨星'},
    'II' : {radius: 7,   label:'輝巨星'},
    'Ib' : {radius: 10,  label:'暗い超巨星'},
    'Iab': {radius: 10,  label:'超巨星'},
    'Ia' : {radius: 10,  label:'明るい超巨星'},
    'Ia+': {radius: 100, label:'極超巨星'},
    'Ia0': {radius: 100, label:'極超巨星'},
  },
  symbols: {
    'And': {label: 'アンドロメダ座'},
    'Mon': {label: 'いっかくじゅう座'},
    'Sgr': {label: 'いて座'},
    'Del': {label: 'いるか座'},
    'Ind': {label: 'インディアン座'},
    'Psc': {label: 'うお座'},
    'Lep': {label: 'うさぎ座'},
    'Boö': {label: 'うしかい座'},
    'Hya': {label: 'うみへび座'},
    'Eri': {label: 'エリダヌス座'},
    'Tau': {label: 'おうし座'},
    'CMa': {label: 'おおいぬ座'},
    'Lup': {label: 'おおかみ座'},
    'UMa': {label: 'おおぐま座'},
    'Vir': {label: 'おとめ座'},
    'Ari': {label: 'おひつじ座'},
    'Ori': {label: 'オリオン座'},
    'Cas': {label: 'カシオペヤ座'},
    'Dor': {label: 'かじき座'},
    'Cnc': {label: 'かに座'},
    'Com': {label: 'かみのけ座'},
    'Cha': {label: 'カメレオン座'},
    'Crv': {label: 'からす座'},
    'CrB': {label: 'かんむり座'},
    'Pic': {label: 'がか座'},
    'Tuc': {label: 'きょしちょう座'},
    'Cam': {label: 'きりん座'},
    'Aur': {label: 'ぎょしゃ座'},
    'Cet': {label: 'くじら座'},
    'Pav': {label: 'くじゃく座'},
    'Cep': {label: 'ケフェウス座'},
    'Cen': {label: 'ケンタウルス座'},
    'Mic': {label: 'けんびきょう座'},
    'CMi': {label: 'こいぬ座'},
    'Equ': {label: 'こうま座'},
    'Vul': {label: 'こぎつね座'},
    'UMi': {label: 'こぐま座'},
    'LMi': {label: 'こじし座'},
    'Crt': {label: 'コップ座'},
    'Lyr': {label: 'こと座'},
    'Cir': {label: 'コンパス座'},
    'Ara': {label: 'さいだん座'},
    'Sco': {label: 'さそり座'},
    'Tri': {label: 'さんかく座'},
    'Leo': {label: 'しし座'},
    'Nor': {label: 'じょうぎ座'},
    'Sct': {label: 'たて座'},
    'Cae': {label: 'ちょうこくぐ座'},
    'Scl': {label: 'ちょうこくしつ座'},
    'Gru': {label: 'つる座'},
    'Lib': {label: 'てんびん座'},
    'Men': {label: 'テーブルさん座'},
    'Lac': {label: 'とかげ座'},
    'Hor': {label: 'とけい座'},
    'Vol': {label: 'とびうお座'},
    'Pup': {label: 'とも座'},
    'Mus': {label: 'はえ座'},
    'Cyg': {label: 'はくちょう座'},
    'Oct': {label: 'はちぶんぎ座'},
    'Col': {label: 'はと座'},
    'Aps': {label: 'ふうちょう座'},
    'Gem': {label: 'ふたご座'},
    'Oph': {label: 'へびつかい座'},
    'Ser': {label: 'へび座'},
    'Her': {label: 'ヘルクレス座'},
    'Peg': {label: 'ペガスス座'},
    'Per': {label: 'ペルセウス座'},
    'Phe': {label: 'ほうおう座'},
    'Vel': {label: 'ほ座'},
    'Tel': {label: 'ぼうえんきょう座'},
    'Ant': {label: 'ポンプ座'},
    'Aqr': {label: 'みずがめ座'},
    'Hyi': {label: 'みずへび座'},
    'CrA': {label: 'みなみのかんむり座'},
    'Cru': {label: 'みなみじゅうじ座'},
    'PsA': {label: 'みなみのうお座'},
    'TrA': {label: 'みなみのさんかく座'},
    'Cap': {label: 'やぎ座'},
    'Lyn': {label: 'やまねこ座'},
    'Sge': {label: 'や座'},
    'Pyx': {label: 'らしんばん座'},
    'Car': {label: 'りゅうこつ座'},
    'Dra': {label: 'りゅう座'},
    'CVn': {label: 'りょうけん座'},
    'Ret': {label: 'レチクル座'},
    'Sex': {label: 'ろくぶんぎ座'},
    'For': {label: 'ろ座'},
    'Aql': {label: 'わし座'},
  },
};